name: dictionaryx
description: English dictionary with about 120.000 entries, based on Wordnet.
version: 0.1.1
repository: https://github.com/xErik/dictionaryx
issue_tracker: https://github.com/xErik/dictionaryx/issues

executables:
  dict:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  lints: ^2.0.0
  path: ^1.8.1
  test: ^1.21.1

 